let Tree = [
	{
		"searchValue": null,
		"createBy": "admin",
		"createTime": "2018-03-16 03:33:00",
		"updateBy": null,
		"updateTime": null,
		"remark": null,
		"dataScope": null,
		"params": {},
		"menuId": 4,
		"menuName": "业务模块",
		"parentName": null,
		"parentId": 0,
		"orderNum": "1",
		"path": "task",
		"component": null,
		"isFrame": "1",
		"menuType": "M",
		"visible": "0",
		"perms": "",
		"icon": "component",
		"children": [
			{
				"searchValue": null,
				"createBy": "admin",
				"createTime": "2019-12-10 07:40:07",
				"updateBy": null,
				"updateTime": null,
				"remark": null,
				"dataScope": null,
				"params": {},
				"menuId": 2156,
				"menuName": "生产总控",
				"parentName": null,
				"parentId": 4,
				"orderNum": "1",
				"path": "sczk",
				"component": null,
				"isFrame": "1",
				"menuType": "M",
				"visible": "0",
				"perms": "",
				"icon": "dict",
				"children": [
					{
						"searchValue": null,
						"createBy": "admin",
						"createTime": "2018-02-28 16:00:00",
						"updateBy": null,
						"updateTime": null,
						"remark": null,
						"dataScope": null,
						"params": {},
						"menuId": 2142,
						"menuName": "铸件单件",
						"parentName": null,
						"parentId": 2156,
						"orderNum": "3",
						"path": "/yf_join_table/铸件单件",
						"component": "system/yf_join_table/yf_join_table_view",
						"isFrame": "1",
						"menuType": "C",
						"visible": "0",
						"perms": "system:join_table:view:铸件单件",
						"icon": "#",
						"children": [
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-02-28 16:00:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 2143,
								"menuName": "铸件单件-查询",
								"parentName": null,
								"parentId": 2142,
								"orderNum": "1",
								"path": "",
								"component": "",
								"isFrame": "1",
								"menuType": "F",
								"visible": "0",
								"perms": "system:join_table:list:铸件单件",
								"icon": "#",
								"children": []
							},
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-02-28 16:00:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 2144,
								"menuName": "铸件单件-新增",
								"parentName": null,
								"parentId": 2142,
								"orderNum": "2",
								"path": "",
								"component": "",
								"isFrame": "1",
								"menuType": "F",
								"visible": "0",
								"perms": "system:join_table:add:铸件单件",
								"icon": "#",
								"children": []
							},
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-02-28 16:00:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 2145,
								"menuName": "铸件单件-修改",
								"parentName": null,
								"parentId": 2142,
								"orderNum": "3",
								"path": "",
								"component": "",
								"isFrame": "1",
								"menuType": "F",
								"visible": "0",
								"perms": "system:join_table:edit:铸件单件",
								"icon": "#",
								"children": []
							},
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-02-28 16:00:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 2146,
								"menuName": "铸件单件-删除",
								"parentName": null,
								"parentId": 2142,
								"orderNum": "4",
								"path": "",
								"component": "",
								"isFrame": "1",
								"menuType": "F",
								"visible": "0",
								"perms": "system:join_table:remove:铸件单件",
								"icon": "#",
								"children": []
							},
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-02-28 16:00:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 2147,
								"menuName": "铸件单件-导入",
								"parentName": null,
								"parentId": 2142,
								"orderNum": "5",
								"path": "",
								"component": "",
								"isFrame": "1",
								"menuType": "F",
								"visible": "0",
								"perms": "system:join_table:import:铸件单件",
								"icon": "#",
								"children": []
							},
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-02-28 16:00:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 2148,
								"menuName": "铸件单件-导出",
								"parentName": null,
								"parentId": 2142,
								"orderNum": "6",
								"path": "",
								"component": "",
								"isFrame": "1",
								"menuType": "F",
								"visible": "0",
								"perms": "system:join_table:export:铸件单件",
								"icon": "#",
								"children": []
							},
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-02-28 16:00:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 2149,
								"menuName": "铸件单件-打印",
								"parentName": null,
								"parentId": 2142,
								"orderNum": "7",
								"path": "",
								"component": "",
								"isFrame": "1",
								"menuType": "F",
								"visible": "0",
								"perms": "system:join_table:print:铸件单件",
								"icon": "#",
								"children": []
							}
						]
					}
				]
			},
			{
				"searchValue": null,
				"createBy": "admin",
				"createTime": "2019-12-10 07:38:44",
				"updateBy": null,
				"updateTime": null,
				"remark": null,
				"dataScope": null,
				"params": {},
				"menuId": 2155,
				"menuName": "技术工艺",
				"parentName": null,
				"parentId": 4,
				"orderNum": "1",
				"path": "jsgy",
				"component": null,
				"isFrame": "1",
				"menuType": "M",
				"visible": "0",
				"perms": "",
				"icon": "star",
				"children": [
					{
						"searchValue": null,
						"createBy": "admin",
						"createTime": "2018-02-28 16:00:00",
						"updateBy": null,
						"updateTime": null,
						"remark": null,
						"dataScope": null,
						"params": {},
						"menuId": 2110,
						"menuName": "产品信息",
						"parentName": null,
						"parentId": 2155,
						"orderNum": "1",
						"path": "/yf_join_table/产品信息",
						"component": "system/yf_join_table/yf_join_table_view",
						"isFrame": "1",
						"menuType": "C",
						"visible": "0",
						"perms": "system:join_table:view:产品信息",
						"icon": "tree-table",
						"children": [
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-02-28 16:00:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 2111,
								"menuName": "产品信息-查询",
								"parentName": null,
								"parentId": 2110,
								"orderNum": "1",
								"path": "",
								"component": "",
								"isFrame": "1",
								"menuType": "F",
								"visible": "0",
								"perms": "system:join_table:list:产品信息",
								"icon": "#",
								"children": []
							},
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-02-28 16:00:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 2112,
								"menuName": "产品信息-新增",
								"parentName": null,
								"parentId": 2110,
								"orderNum": "2",
								"path": "",
								"component": "",
								"isFrame": "1",
								"menuType": "F",
								"visible": "0",
								"perms": "system:join_table:add:产品信息",
								"icon": "#",
								"children": []
							},
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-02-28 16:00:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 2113,
								"menuName": "产品信息-修改",
								"parentName": null,
								"parentId": 2110,
								"orderNum": "3",
								"path": "",
								"component": "",
								"isFrame": "1",
								"menuType": "F",
								"visible": "0",
								"perms": "system:join_table:edit:产品信息",
								"icon": "#",
								"children": []
							},
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-02-28 16:00:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 2114,
								"menuName": "产品信息-删除",
								"parentName": null,
								"parentId": 2110,
								"orderNum": "4",
								"path": "",
								"component": "",
								"isFrame": "1",
								"menuType": "F",
								"visible": "0",
								"perms": "system:join_table:remove:产品信息",
								"icon": "#",
								"children": []
							},
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-02-28 16:00:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 2115,
								"menuName": "产品信息-导入",
								"parentName": null,
								"parentId": 2110,
								"orderNum": "5",
								"path": "",
								"component": "",
								"isFrame": "1",
								"menuType": "F",
								"visible": "0",
								"perms": "system:join_table:import:产品信息",
								"icon": "#",
								"children": []
							},
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-02-28 16:00:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 2116,
								"menuName": "产品信息-导出",
								"parentName": null,
								"parentId": 2110,
								"orderNum": "6",
								"path": "",
								"component": "",
								"isFrame": "1",
								"menuType": "F",
								"visible": "0",
								"perms": "system:join_table:export:产品信息",
								"icon": "#",
								"children": []
							},
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-02-28 16:00:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 2117,
								"menuName": "产品信息-打印",
								"parentName": null,
								"parentId": 2110,
								"orderNum": "7",
								"path": "",
								"component": "",
								"isFrame": "1",
								"menuType": "F",
								"visible": "0",
								"perms": "system:join_table:print:产品信息",
								"icon": "#",
								"children": []
							}
						]
					}
				]
			},
			{
				"searchValue": null,
				"createBy": "admin",
				"createTime": "2018-02-28 16:00:00",
				"updateBy": null,
				"updateTime": null,
				"remark": null,
				"dataScope": null,
				"params": {},
				"menuId": 2126,
				"menuName": "客户信息",
				"parentName": null,
				"parentId": 4,
				"orderNum": "2",
				"path": "/yf_join_table/客户信息",
				"component": "system/yf_join_table/yf_join_table_view",
				"isFrame": "1",
				"menuType": "C",
				"visible": "0",
				"perms": "system:join_table:view:客户信息",
				"icon": "#",
				"children": [
					{
						"searchValue": null,
						"createBy": "admin",
						"createTime": "2018-02-28 16:00:00",
						"updateBy": null,
						"updateTime": null,
						"remark": null,
						"dataScope": null,
						"params": {},
						"menuId": 2127,
						"menuName": "客户信息-查询",
						"parentName": null,
						"parentId": 2126,
						"orderNum": "1",
						"path": "",
						"component": "",
						"isFrame": "1",
						"menuType": "F",
						"visible": "0",
						"perms": "system:join_table:list:客户信息",
						"icon": "#",
						"children": []
					},
					{
						"searchValue": null,
						"createBy": "admin",
						"createTime": "2018-02-28 16:00:00",
						"updateBy": null,
						"updateTime": null,
						"remark": null,
						"dataScope": null,
						"params": {},
						"menuId": 2128,
						"menuName": "客户信息-新增",
						"parentName": null,
						"parentId": 2126,
						"orderNum": "2",
						"path": "",
						"component": "",
						"isFrame": "1",
						"menuType": "F",
						"visible": "0",
						"perms": "system:join_table:add:客户信息",
						"icon": "#",
						"children": []
					},
					{
						"searchValue": null,
						"createBy": "admin",
						"createTime": "2018-02-28 16:00:00",
						"updateBy": null,
						"updateTime": null,
						"remark": null,
						"dataScope": null,
						"params": {},
						"menuId": 2129,
						"menuName": "客户信息-修改",
						"parentName": null,
						"parentId": 2126,
						"orderNum": "3",
						"path": "",
						"component": "",
						"isFrame": "1",
						"menuType": "F",
						"visible": "0",
						"perms": "system:join_table:edit:客户信息",
						"icon": "#",
						"children": []
					},
					{
						"searchValue": null,
						"createBy": "admin",
						"createTime": "2018-02-28 16:00:00",
						"updateBy": null,
						"updateTime": null,
						"remark": null,
						"dataScope": null,
						"params": {},
						"menuId": 2130,
						"menuName": "客户信息-删除",
						"parentName": null,
						"parentId": 2126,
						"orderNum": "4",
						"path": "",
						"component": "",
						"isFrame": "1",
						"menuType": "F",
						"visible": "0",
						"perms": "system:join_table:remove:客户信息",
						"icon": "#",
						"children": []
					},
					{
						"searchValue": null,
						"createBy": "admin",
						"createTime": "2018-02-28 16:00:00",
						"updateBy": null,
						"updateTime": null,
						"remark": null,
						"dataScope": null,
						"params": {},
						"menuId": 2131,
						"menuName": "客户信息-导入",
						"parentName": null,
						"parentId": 2126,
						"orderNum": "5",
						"path": "",
						"component": "",
						"isFrame": "1",
						"menuType": "F",
						"visible": "0",
						"perms": "system:join_table:import:客户信息",
						"icon": "#",
						"children": []
					},
					{
						"searchValue": null,
						"createBy": "admin",
						"createTime": "2018-02-28 16:00:00",
						"updateBy": null,
						"updateTime": null,
						"remark": null,
						"dataScope": null,
						"params": {},
						"menuId": 2132,
						"menuName": "客户信息-导出",
						"parentName": null,
						"parentId": 2126,
						"orderNum": "6",
						"path": "",
						"component": "",
						"isFrame": "1",
						"menuType": "F",
						"visible": "0",
						"perms": "system:join_table:export:客户信息",
						"icon": "#",
						"children": []
					},
					{
						"searchValue": null,
						"createBy": "admin",
						"createTime": "2018-02-28 16:00:00",
						"updateBy": null,
						"updateTime": null,
						"remark": null,
						"dataScope": null,
						"params": {},
						"menuId": 2133,
						"menuName": "客户信息-打印",
						"parentName": null,
						"parentId": 2126,
						"orderNum": "7",
						"path": "",
						"component": "",
						"isFrame": "1",
						"menuType": "F",
						"visible": "0",
						"perms": "system:join_table:print:客户信息",
						"icon": "#",
						"children": []
					}
				]
			},
			{
				"searchValue": null,
				"createBy": "admin",
				"createTime": "2018-02-28 16:00:00",
				"updateBy": null,
				"updateTime": null,
				"remark": null,
				"dataScope": null,
				"params": {},
				"menuId": 2157,
				"menuName": "订单录入",
				"parentName": null,
				"parentId": 4,
				"orderNum": "3",
				"path": "/yf_join_table/订单录入",
				"component": "system/yf_join_table/yf_join_table_view",
				"isFrame": "1",
				"menuType": "C",
				"visible": "0",
				"perms": "system:join_table:view:订单录入",
				"icon": "#",
				"children": [
					{
						"searchValue": null,
						"createBy": "admin",
						"createTime": "2018-02-28 16:00:00",
						"updateBy": null,
						"updateTime": null,
						"remark": null,
						"dataScope": null,
						"params": {},
						"menuId": 2158,
						"menuName": "订单录入-查询",
						"parentName": null,
						"parentId": 2157,
						"orderNum": "1",
						"path": "",
						"component": "",
						"isFrame": "1",
						"menuType": "F",
						"visible": "0",
						"perms": "system:join_table:list:订单录入",
						"icon": "#",
						"children": []
					},
					{
						"searchValue": null,
						"createBy": "admin",
						"createTime": "2018-02-28 16:00:00",
						"updateBy": null,
						"updateTime": null,
						"remark": null,
						"dataScope": null,
						"params": {},
						"menuId": 2159,
						"menuName": "订单录入-新增",
						"parentName": null,
						"parentId": 2157,
						"orderNum": "2",
						"path": "",
						"component": "",
						"isFrame": "1",
						"menuType": "F",
						"visible": "0",
						"perms": "system:join_table:add:订单录入",
						"icon": "#",
						"children": []
					},
					{
						"searchValue": null,
						"createBy": "admin",
						"createTime": "2018-02-28 16:00:00",
						"updateBy": null,
						"updateTime": null,
						"remark": null,
						"dataScope": null,
						"params": {},
						"menuId": 2160,
						"menuName": "订单录入-修改",
						"parentName": null,
						"parentId": 2157,
						"orderNum": "3",
						"path": "",
						"component": "",
						"isFrame": "1",
						"menuType": "F",
						"visible": "0",
						"perms": "system:join_table:edit:订单录入",
						"icon": "#",
						"children": []
					},
					{
						"searchValue": null,
						"createBy": "admin",
						"createTime": "2018-02-28 16:00:00",
						"updateBy": null,
						"updateTime": null,
						"remark": null,
						"dataScope": null,
						"params": {},
						"menuId": 2161,
						"menuName": "订单录入-删除",
						"parentName": null,
						"parentId": 2157,
						"orderNum": "4",
						"path": "",
						"component": "",
						"isFrame": "1",
						"menuType": "F",
						"visible": "0",
						"perms": "system:join_table:remove:订单录入",
						"icon": "#",
						"children": []
					},
					{
						"searchValue": null,
						"createBy": "admin",
						"createTime": "2018-02-28 16:00:00",
						"updateBy": null,
						"updateTime": null,
						"remark": null,
						"dataScope": null,
						"params": {},
						"menuId": 2162,
						"menuName": "订单录入-导入",
						"parentName": null,
						"parentId": 2157,
						"orderNum": "5",
						"path": "",
						"component": "",
						"isFrame": "1",
						"menuType": "F",
						"visible": "0",
						"perms": "system:join_table:import:订单录入",
						"icon": "#",
						"children": []
					},
					{
						"searchValue": null,
						"createBy": "admin",
						"createTime": "2018-02-28 16:00:00",
						"updateBy": null,
						"updateTime": null,
						"remark": null,
						"dataScope": null,
						"params": {},
						"menuId": 2163,
						"menuName": "订单录入-导出",
						"parentName": null,
						"parentId": 2157,
						"orderNum": "6",
						"path": "",
						"component": "",
						"isFrame": "1",
						"menuType": "F",
						"visible": "0",
						"perms": "system:join_table:export:订单录入",
						"icon": "#",
						"children": []
					},
					{
						"searchValue": null,
						"createBy": "admin",
						"createTime": "2018-02-28 16:00:00",
						"updateBy": null,
						"updateTime": null,
						"remark": null,
						"dataScope": null,
						"params": {},
						"menuId": 2164,
						"menuName": "订单录入-打印",
						"parentName": null,
						"parentId": 2157,
						"orderNum": "7",
						"path": "",
						"component": "",
						"isFrame": "1",
						"menuType": "F",
						"visible": "0",
						"perms": "system:join_table:print:订单录入",
						"icon": "#",
						"children": []
					}
				]
			},
			{
				"searchValue": null,
				"createBy": "admin",
				"createTime": "2018-02-28 16:00:00",
				"updateBy": null,
				"updateTime": null,
				"remark": null,
				"dataScope": null,
				"params": {},
				"menuId": 2165,
				"menuName": "铸件工艺单",
				"parentName": null,
				"parentId": 4,
				"orderNum": "4",
				"path": "/yf_join_table/铸件工艺单",
				"component": "system/yf_join_table/yf_join_table_view",
				"isFrame": "1",
				"menuType": "C",
				"visible": "0",
				"perms": "system:join_table:view:铸件工艺单",
				"icon": "#",
				"children": [
					{
						"searchValue": null,
						"createBy": "admin",
						"createTime": "2018-02-28 16:00:00",
						"updateBy": null,
						"updateTime": null,
						"remark": null,
						"dataScope": null,
						"params": {},
						"menuId": 2166,
						"menuName": "铸件工艺单-查询",
						"parentName": null,
						"parentId": 2165,
						"orderNum": "1",
						"path": "",
						"component": "",
						"isFrame": "1",
						"menuType": "F",
						"visible": "0",
						"perms": "system:join_table:list:铸件工艺单",
						"icon": "#",
						"children": []
					},
					{
						"searchValue": null,
						"createBy": "admin",
						"createTime": "2018-02-28 16:00:00",
						"updateBy": null,
						"updateTime": null,
						"remark": null,
						"dataScope": null,
						"params": {},
						"menuId": 2167,
						"menuName": "铸件工艺单-新增",
						"parentName": null,
						"parentId": 2165,
						"orderNum": "2",
						"path": "",
						"component": "",
						"isFrame": "1",
						"menuType": "F",
						"visible": "0",
						"perms": "system:join_table:add:铸件工艺单",
						"icon": "#",
						"children": []
					},
					{
						"searchValue": null,
						"createBy": "admin",
						"createTime": "2018-02-28 16:00:00",
						"updateBy": null,
						"updateTime": null,
						"remark": null,
						"dataScope": null,
						"params": {},
						"menuId": 2168,
						"menuName": "铸件工艺单-修改",
						"parentName": null,
						"parentId": 2165,
						"orderNum": "3",
						"path": "",
						"component": "",
						"isFrame": "1",
						"menuType": "F",
						"visible": "0",
						"perms": "system:join_table:edit:铸件工艺单",
						"icon": "#",
						"children": []
					},
					{
						"searchValue": null,
						"createBy": "admin",
						"createTime": "2018-02-28 16:00:00",
						"updateBy": null,
						"updateTime": null,
						"remark": null,
						"dataScope": null,
						"params": {},
						"menuId": 2169,
						"menuName": "铸件工艺单-删除",
						"parentName": null,
						"parentId": 2165,
						"orderNum": "4",
						"path": "",
						"component": "",
						"isFrame": "1",
						"menuType": "F",
						"visible": "0",
						"perms": "system:join_table:remove:铸件工艺单",
						"icon": "#",
						"children": []
					},
					{
						"searchValue": null,
						"createBy": "admin",
						"createTime": "2018-02-28 16:00:00",
						"updateBy": null,
						"updateTime": null,
						"remark": null,
						"dataScope": null,
						"params": {},
						"menuId": 2170,
						"menuName": "铸件工艺单-导入",
						"parentName": null,
						"parentId": 2165,
						"orderNum": "5",
						"path": "",
						"component": "",
						"isFrame": "1",
						"menuType": "F",
						"visible": "0",
						"perms": "system:join_table:import:铸件工艺单",
						"icon": "#",
						"children": []
					},
					{
						"searchValue": null,
						"createBy": "admin",
						"createTime": "2018-02-28 16:00:00",
						"updateBy": null,
						"updateTime": null,
						"remark": null,
						"dataScope": null,
						"params": {},
						"menuId": 2171,
						"menuName": "铸件工艺单-导出",
						"parentName": null,
						"parentId": 2165,
						"orderNum": "6",
						"path": "",
						"component": "",
						"isFrame": "1",
						"menuType": "F",
						"visible": "0",
						"perms": "system:join_table:export:铸件工艺单",
						"icon": "#",
						"children": []
					},
					{
						"searchValue": null,
						"createBy": "admin",
						"createTime": "2018-02-28 16:00:00",
						"updateBy": null,
						"updateTime": null,
						"remark": null,
						"dataScope": null,
						"params": {},
						"menuId": 2172,
						"menuName": "铸件工艺单-打印",
						"parentName": null,
						"parentId": 2165,
						"orderNum": "7",
						"path": "",
						"component": "",
						"isFrame": "1",
						"menuType": "F",
						"visible": "0",
						"perms": "system:join_table:print:铸件工艺单",
						"icon": "#",
						"children": []
					}
				]
			}
		]
	},
	{
		"searchValue": null,
		"createBy": "admin",
		"createTime": "2018-03-16 03:33:00",
		"updateBy": null,
		"updateTime": null,
		"remark": null,
		"dataScope": null,
		"params": {},
		"menuId": 5,
		"menuName": "模块管理",
		"parentName": null,
		"parentId": 0,
		"orderNum": "2",
		"path": "yf_module_settings",
		"component": null,
		"isFrame": "1",
		"menuType": "M",
		"visible": "0",
		"perms": "",
		"icon": "edit",
		"children": [
			{
				"searchValue": null,
				"createBy": "admin",
				"createTime": "2018-03-16 03:33:00",
				"updateBy": null,
				"updateTime": null,
				"remark": null,
				"dataScope": null,
				"params": {},
				"menuId": 116,
				"menuName": "联合表信息",
				"parentName": null,
				"parentId": 5,
				"orderNum": "1",
				"path": "/yf_join_table_info",
				"component": "system/yf_join_table/yf_join_table_info",
				"isFrame": "1",
				"menuType": "C",
				"visible": "0",
				"perms": "system:admin",
				"icon": "#",
				"children": []
			},
			{
				"searchValue": null,
				"createBy": "admin",
				"createTime": "2018-03-16 03:33:00",
				"updateBy": null,
				"updateTime": null,
				"remark": null,
				"dataScope": null,
				"params": {},
				"menuId": 117,
				"menuName": "联合表字段属性",
				"parentName": null,
				"parentId": 5,
				"orderNum": "2",
				"path": "/yf_join_table_column_info",
				"component": "system/yf_join_table/yf_join_table_column_info",
				"isFrame": "1",
				"menuType": "C",
				"visible": "0",
				"perms": "system:admin",
				"icon": "#",
				"children": []
			},
			{
				"searchValue": null,
				"createBy": "admin",
				"createTime": "2018-03-16 03:33:00",
				"updateBy": null,
				"updateTime": null,
				"remark": null,
				"dataScope": null,
				"params": {},
				"menuId": 118,
				"menuName": "联合表字段自定义",
				"parentName": null,
				"parentId": 5,
				"orderNum": "3",
				"path": "/yf_join_table_column_user",
				"component": "system/yf_join_table/yf_join_table_column_user",
				"isFrame": "1",
				"menuType": "C",
				"visible": "0",
				"perms": "system:admin",
				"icon": "#",
				"children": []
			},
			{
				"searchValue": null,
				"createBy": "admin",
				"createTime": "2018-03-16 03:33:00",
				"updateBy": null,
				"updateTime": null,
				"remark": null,
				"dataScope": null,
				"params": {},
				"menuId": 119,
				"menuName": "联合表跳转设置",
				"parentName": null,
				"parentId": 5,
				"orderNum": "4",
				"path": "/yf_join_table_jump",
				"component": "system/yf_join_table/yf_join_table_jump",
				"isFrame": "1",
				"menuType": "C",
				"visible": "0",
				"perms": "system:admin",
				"icon": "#",
				"children": []
			}
		]
	},
	{
		"searchValue": null,
		"createBy": "admin",
		"createTime": "2018-03-16 03:33:00",
		"updateBy": null,
		"updateTime": null,
		"remark": null,
		"dataScope": null,
		"params": {},
		"menuId": 1,
		"menuName": "系统管理",
		"parentName": null,
		"parentId": 0,
		"orderNum": "3",
		"path": "system",
		"component": null,
		"isFrame": "1",
		"menuType": "M",
		"visible": "0",
		"perms": "",
		"icon": "guide",
		"children": [
			{
				"searchValue": null,
				"createBy": "admin",
				"createTime": "2019-12-10 07:28:43",
				"updateBy": null,
				"updateTime": null,
				"remark": null,
				"dataScope": null,
				"params": {},
				"menuId": 2152,
				"menuName": "系统设置",
				"parentName": null,
				"parentId": 1,
				"orderNum": "1",
				"path": "monitor1",
				"component": null,
				"isFrame": "1",
				"menuType": "M",
				"visible": "0",
				"perms": "",
				"icon": "guide",
				"children": [
					{
						"searchValue": null,
						"createBy": "admin",
						"createTime": "2018-03-16 03:33:00",
						"updateBy": null,
						"updateTime": null,
						"remark": null,
						"dataScope": null,
						"params": {},
						"menuId": 100,
						"menuName": "用户管理",
						"parentName": null,
						"parentId": 2152,
						"orderNum": "1",
						"path": "user",
						"component": "system/user/index",
						"isFrame": "1",
						"menuType": "M",
						"visible": "0",
						"perms": "system:user:view",
						"icon": "guide",
						"children": [
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-03-16 03:33:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 1000,
								"menuName": "用户查询",
								"parentName": null,
								"parentId": 100,
								"orderNum": "1",
								"path": "",
								"component": "",
								"isFrame": "1",
								"menuType": "F",
								"visible": "0",
								"perms": "system:user:list",
								"icon": "#",
								"children": []
							},
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-03-16 03:33:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 1001,
								"menuName": "用户新增",
								"parentName": null,
								"parentId": 100,
								"orderNum": "2",
								"path": "",
								"component": "",
								"isFrame": "1",
								"menuType": "F",
								"visible": "0",
								"perms": "system:user:add",
								"icon": "#",
								"children": []
							},
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-03-16 03:33:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 1002,
								"menuName": "用户修改",
								"parentName": null,
								"parentId": 100,
								"orderNum": "3",
								"path": "",
								"component": "",
								"isFrame": "1",
								"menuType": "F",
								"visible": "0",
								"perms": "system:user:edit",
								"icon": "#",
								"children": []
							},
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-03-16 03:33:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 1003,
								"menuName": "用户删除",
								"parentName": null,
								"parentId": 100,
								"orderNum": "4",
								"path": "",
								"component": "",
								"isFrame": "1",
								"menuType": "F",
								"visible": "0",
								"perms": "system:user:remove",
								"icon": "#",
								"children": []
							},
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-03-16 03:33:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 1004,
								"menuName": "用户导出",
								"parentName": null,
								"parentId": 100,
								"orderNum": "5",
								"path": "",
								"component": "",
								"isFrame": "1",
								"menuType": "F",
								"visible": "0",
								"perms": "system:user:export",
								"icon": "#",
								"children": []
							},
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-03-16 03:33:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 1005,
								"menuName": "用户导入",
								"parentName": null,
								"parentId": 100,
								"orderNum": "6",
								"path": "",
								"component": "",
								"isFrame": "1",
								"menuType": "F",
								"visible": "0",
								"perms": "system:user:import",
								"icon": "#",
								"children": []
							},
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-03-16 03:33:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 1006,
								"menuName": "重置密码",
								"parentName": null,
								"parentId": 100,
								"orderNum": "7",
								"path": "",
								"component": "",
								"isFrame": "1",
								"menuType": "F",
								"visible": "0",
								"perms": "system:user:resetPwd",
								"icon": "#",
								"children": []
							}
						]
					},
					{
						"searchValue": null,
						"createBy": "admin",
						"createTime": "2018-03-16 03:33:00",
						"updateBy": null,
						"updateTime": null,
						"remark": null,
						"dataScope": null,
						"params": {},
						"menuId": 101,
						"menuName": "角色管理",
						"parentName": null,
						"parentId": 2152,
						"orderNum": "2",
						"path": "role",
						"component": "system/role/index",
						"isFrame": "1",
						"menuType": "C",
						"visible": "0",
						"perms": "system:role:view",
						"icon": "#",
						"children": [
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-03-16 03:33:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 1007,
								"menuName": "角色查询",
								"parentName": null,
								"parentId": 101,
								"orderNum": "1",
								"path": "",
								"component": "",
								"isFrame": "1",
								"menuType": "F",
								"visible": "0",
								"perms": "system:role:list",
								"icon": "#",
								"children": []
							},
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-03-16 03:33:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 1008,
								"menuName": "角色新增",
								"parentName": null,
								"parentId": 101,
								"orderNum": "2",
								"path": "",
								"component": "",
								"isFrame": "1",
								"menuType": "F",
								"visible": "0",
								"perms": "system:role:add",
								"icon": "#",
								"children": []
							},
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-03-16 03:33:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 1009,
								"menuName": "角色修改",
								"parentName": null,
								"parentId": 101,
								"orderNum": "3",
								"path": "",
								"component": "",
								"isFrame": "1",
								"menuType": "F",
								"visible": "0",
								"perms": "system:role:edit",
								"icon": "#",
								"children": []
							},
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-03-16 03:33:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 1010,
								"menuName": "角色删除",
								"parentName": null,
								"parentId": 101,
								"orderNum": "4",
								"path": "",
								"component": "",
								"isFrame": "1",
								"menuType": "F",
								"visible": "0",
								"perms": "system:role:remove",
								"icon": "#",
								"children": []
							},
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-03-16 03:33:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 1011,
								"menuName": "角色导出",
								"parentName": null,
								"parentId": 101,
								"orderNum": "5",
								"path": "",
								"component": "",
								"isFrame": "1",
								"menuType": "F",
								"visible": "0",
								"perms": "system:role:export",
								"icon": "#",
								"children": []
							}
						]
					},
					{
						"searchValue": null,
						"createBy": "admin",
						"createTime": "2018-03-16 03:33:00",
						"updateBy": null,
						"updateTime": null,
						"remark": null,
						"dataScope": null,
						"params": {},
						"menuId": 102,
						"menuName": "菜单管理",
						"parentName": null,
						"parentId": 2152,
						"orderNum": "3",
						"path": "menu",
						"component": "system/menu/index",
						"isFrame": "1",
						"menuType": "C",
						"visible": "0",
						"perms": "system:menu:view",
						"icon": "#",
						"children": [
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-03-16 03:33:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 1012,
								"menuName": "菜单查询",
								"parentName": null,
								"parentId": 102,
								"orderNum": "1",
								"path": "",
								"component": "",
								"isFrame": "1",
								"menuType": "F",
								"visible": "0",
								"perms": "system:menu:list",
								"icon": "#",
								"children": []
							},
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-03-16 03:33:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 1013,
								"menuName": "菜单新增",
								"parentName": null,
								"parentId": 102,
								"orderNum": "2",
								"path": "",
								"component": "",
								"isFrame": "1",
								"menuType": "F",
								"visible": "0",
								"perms": "system:menu:add",
								"icon": "#",
								"children": []
							},
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-03-16 03:33:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 1014,
								"menuName": "菜单修改",
								"parentName": null,
								"parentId": 102,
								"orderNum": "3",
								"path": "",
								"component": "",
								"isFrame": "1",
								"menuType": "F",
								"visible": "0",
								"perms": "system:menu:edit",
								"icon": "#",
								"children": []
							},
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-03-16 03:33:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 1015,
								"menuName": "菜单删除",
								"parentName": null,
								"parentId": 102,
								"orderNum": "4",
								"path": "",
								"component": "",
								"isFrame": "1",
								"menuType": "F",
								"visible": "0",
								"perms": "system:menu:remove",
								"icon": "#",
								"children": []
							}
						]
					},
					{
						"searchValue": null,
						"createBy": "admin",
						"createTime": "2018-03-16 03:33:00",
						"updateBy": null,
						"updateTime": null,
						"remark": null,
						"dataScope": null,
						"params": {},
						"menuId": 103,
						"menuName": "部门管理",
						"parentName": null,
						"parentId": 2152,
						"orderNum": "4",
						"path": "dept",
						"component": "system/dept/index",
						"isFrame": "1",
						"menuType": "C",
						"visible": "0",
						"perms": "system:dept:view",
						"icon": "#",
						"children": [
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-03-16 03:33:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 1016,
								"menuName": "部门查询",
								"parentName": null,
								"parentId": 103,
								"orderNum": "1",
								"path": "",
								"component": "",
								"isFrame": "1",
								"menuType": "F",
								"visible": "0",
								"perms": "system:dept:list",
								"icon": "#",
								"children": []
							},
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-03-16 03:33:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 1017,
								"menuName": "部门新增",
								"parentName": null,
								"parentId": 103,
								"orderNum": "2",
								"path": "",
								"component": "",
								"isFrame": "1",
								"menuType": "F",
								"visible": "0",
								"perms": "system:dept:add",
								"icon": "#",
								"children": []
							},
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-03-16 03:33:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 1018,
								"menuName": "部门修改",
								"parentName": null,
								"parentId": 103,
								"orderNum": "3",
								"path": "",
								"component": "",
								"isFrame": "1",
								"menuType": "F",
								"visible": "0",
								"perms": "system:dept:edit",
								"icon": "#",
								"children": []
							},
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-03-16 03:33:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 1019,
								"menuName": "部门删除",
								"parentName": null,
								"parentId": 103,
								"orderNum": "4",
								"path": "",
								"component": "",
								"isFrame": "1",
								"menuType": "F",
								"visible": "0",
								"perms": "system:dept:remove",
								"icon": "#",
								"children": []
							}
						]
					},
					{
						"searchValue": null,
						"createBy": "admin",
						"createTime": "2018-03-16 03:33:00",
						"updateBy": null,
						"updateTime": null,
						"remark": null,
						"dataScope": null,
						"params": {},
						"menuId": 104,
						"menuName": "岗位管理",
						"parentName": null,
						"parentId": 2152,
						"orderNum": "5",
						"path": "post",
						"component": "system/post/index",
						"isFrame": "1",
						"menuType": "C",
						"visible": "0",
						"perms": "system:post:view",
						"icon": "#",
						"children": [
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-03-16 03:33:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 1020,
								"menuName": "岗位查询",
								"parentName": null,
								"parentId": 104,
								"orderNum": "1",
								"path": "",
								"component": "",
								"isFrame": "1",
								"menuType": "F",
								"visible": "0",
								"perms": "system:post:list",
								"icon": "#",
								"children": []
							},
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-03-16 03:33:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 1021,
								"menuName": "岗位新增",
								"parentName": null,
								"parentId": 104,
								"orderNum": "2",
								"path": "",
								"component": "",
								"isFrame": "1",
								"menuType": "F",
								"visible": "0",
								"perms": "system:post:add",
								"icon": "#",
								"children": []
							},
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-03-16 03:33:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 1022,
								"menuName": "岗位修改",
								"parentName": null,
								"parentId": 104,
								"orderNum": "3",
								"path": "",
								"component": "",
								"isFrame": "1",
								"menuType": "F",
								"visible": "0",
								"perms": "system:post:edit",
								"icon": "#",
								"children": []
							},
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-03-16 03:33:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 1023,
								"menuName": "岗位删除",
								"parentName": null,
								"parentId": 104,
								"orderNum": "4",
								"path": "",
								"component": "",
								"isFrame": "1",
								"menuType": "F",
								"visible": "0",
								"perms": "system:post:remove",
								"icon": "#",
								"children": []
							},
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-03-16 03:33:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 1024,
								"menuName": "岗位导出",
								"parentName": null,
								"parentId": 104,
								"orderNum": "5",
								"path": "",
								"component": "",
								"isFrame": "1",
								"menuType": "F",
								"visible": "0",
								"perms": "system:post:export",
								"icon": "#",
								"children": []
							}
						]
					},
					{
						"searchValue": null,
						"createBy": "admin",
						"createTime": "2018-03-16 03:33:00",
						"updateBy": null,
						"updateTime": null,
						"remark": null,
						"dataScope": null,
						"params": {},
						"menuId": 105,
						"menuName": "字典管理",
						"parentName": null,
						"parentId": 2152,
						"orderNum": "6",
						"path": "dict",
						"component": "system/dict/index",
						"isFrame": "1",
						"menuType": "C",
						"visible": "0",
						"perms": "system:dict:view",
						"icon": "#",
						"children": [
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-03-16 03:33:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 1025,
								"menuName": "字典查询",
								"parentName": null,
								"parentId": 105,
								"orderNum": "1",
								"path": "",
								"component": "",
								"isFrame": "1",
								"menuType": "F",
								"visible": "0",
								"perms": "system:dict:list",
								"icon": "#",
								"children": []
							},
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-03-16 03:33:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 1026,
								"menuName": "字典新增",
								"parentName": null,
								"parentId": 105,
								"orderNum": "2",
								"path": "",
								"component": "",
								"isFrame": "1",
								"menuType": "F",
								"visible": "0",
								"perms": "system:dict:add",
								"icon": "#",
								"children": []
							},
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-03-16 03:33:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 1027,
								"menuName": "字典修改",
								"parentName": null,
								"parentId": 105,
								"orderNum": "3",
								"path": "",
								"component": "",
								"isFrame": "1",
								"menuType": "F",
								"visible": "0",
								"perms": "system:dict:edit",
								"icon": "#",
								"children": []
							},
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-03-16 03:33:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 1028,
								"menuName": "字典删除",
								"parentName": null,
								"parentId": 105,
								"orderNum": "4",
								"path": "",
								"component": "",
								"isFrame": "1",
								"menuType": "F",
								"visible": "0",
								"perms": "system:dict:remove",
								"icon": "#",
								"children": []
							},
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-03-16 03:33:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 1029,
								"menuName": "字典导出",
								"parentName": null,
								"parentId": 105,
								"orderNum": "5",
								"path": "",
								"component": "",
								"isFrame": "1",
								"menuType": "F",
								"visible": "0",
								"perms": "system:dict:export",
								"icon": "#",
								"children": []
							}
						]
					},
					{
						"searchValue": null,
						"createBy": "admin",
						"createTime": "2018-03-16 03:33:00",
						"updateBy": null,
						"updateTime": null,
						"remark": null,
						"dataScope": null,
						"params": {},
						"menuId": 106,
						"menuName": "参数设置",
						"parentName": null,
						"parentId": 2152,
						"orderNum": "7",
						"path": "config",
						"component": "system/config/index",
						"isFrame": "1",
						"menuType": "C",
						"visible": "0",
						"perms": "system:config:view",
						"icon": "#",
						"children": [
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-03-16 03:33:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 1030,
								"menuName": "参数查询",
								"parentName": null,
								"parentId": 106,
								"orderNum": "1",
								"path": "",
								"component": "",
								"isFrame": "1",
								"menuType": "F",
								"visible": "0",
								"perms": "system:config:list",
								"icon": "#",
								"children": []
							},
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-03-16 03:33:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 1031,
								"menuName": "参数新增",
								"parentName": null,
								"parentId": 106,
								"orderNum": "2",
								"path": "",
								"component": "",
								"isFrame": "1",
								"menuType": "F",
								"visible": "0",
								"perms": "system:config:add",
								"icon": "#",
								"children": []
							},
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-03-16 03:33:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 1032,
								"menuName": "参数修改",
								"parentName": null,
								"parentId": 106,
								"orderNum": "3",
								"path": "",
								"component": "",
								"isFrame": "1",
								"menuType": "F",
								"visible": "0",
								"perms": "system:config:edit",
								"icon": "#",
								"children": []
							},
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-03-16 03:33:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 1033,
								"menuName": "参数删除",
								"parentName": null,
								"parentId": 106,
								"orderNum": "4",
								"path": "",
								"component": "",
								"isFrame": "1",
								"menuType": "F",
								"visible": "0",
								"perms": "system:config:remove",
								"icon": "#",
								"children": []
							},
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-03-16 03:33:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 1034,
								"menuName": "参数导出",
								"parentName": null,
								"parentId": 106,
								"orderNum": "5",
								"path": "",
								"component": "",
								"isFrame": "1",
								"menuType": "F",
								"visible": "0",
								"perms": "system:config:export",
								"icon": "#",
								"children": []
							}
						]
					},
					{
						"searchValue": null,
						"createBy": "admin",
						"createTime": "2018-03-16 03:33:00",
						"updateBy": null,
						"updateTime": null,
						"remark": null,
						"dataScope": null,
						"params": {},
						"menuId": 107,
						"menuName": "通知公告",
						"parentName": null,
						"parentId": 2152,
						"orderNum": "8",
						"path": "notice",
						"component": "system/notice/index",
						"isFrame": "1",
						"menuType": "C",
						"visible": "0",
						"perms": "system:notice:view",
						"icon": "#",
						"children": [
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-03-16 03:33:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 1035,
								"menuName": "公告查询",
								"parentName": null,
								"parentId": 107,
								"orderNum": "1",
								"path": "",
								"component": "",
								"isFrame": "1",
								"menuType": "F",
								"visible": "0",
								"perms": "system:notice:list",
								"icon": "#",
								"children": []
							},
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-03-16 03:33:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 1036,
								"menuName": "公告新增",
								"parentName": null,
								"parentId": 107,
								"orderNum": "2",
								"path": "",
								"component": "",
								"isFrame": "1",
								"menuType": "F",
								"visible": "0",
								"perms": "system:notice:add",
								"icon": "#",
								"children": []
							},
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-03-16 03:33:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 1037,
								"menuName": "公告修改",
								"parentName": null,
								"parentId": 107,
								"orderNum": "3",
								"path": "",
								"component": "",
								"isFrame": "1",
								"menuType": "F",
								"visible": "0",
								"perms": "system:notice:edit",
								"icon": "#",
								"children": []
							},
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-03-16 03:33:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 1038,
								"menuName": "公告删除",
								"parentName": null,
								"parentId": 107,
								"orderNum": "4",
								"path": "",
								"component": "",
								"isFrame": "1",
								"menuType": "F",
								"visible": "0",
								"perms": "system:notice:remove",
								"icon": "#",
								"children": []
							}
						]
					},
					{
						"searchValue": null,
						"createBy": "admin",
						"createTime": "2018-03-16 03:33:00",
						"updateBy": null,
						"updateTime": null,
						"remark": null,
						"dataScope": null,
						"params": {},
						"menuId": 108,
						"menuName": "日志管理",
						"parentName": null,
						"parentId": 2152,
						"orderNum": "9",
						"path": "log",
						"component": "system/log/index",
						"isFrame": "1",
						"menuType": "M",
						"visible": "0",
						"perms": "",
						"icon": "#",
						"children": [
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-03-16 03:33:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 500,
								"menuName": "操作日志",
								"parentName": null,
								"parentId": 108,
								"orderNum": "1",
								"path": "operlog",
								"component": "monitor/operlog/index",
								"isFrame": "1",
								"menuType": "C",
								"visible": "0",
								"perms": "monitor:operlog:view",
								"icon": "#",
								"children": [
									{
										"searchValue": null,
										"createBy": "admin",
										"createTime": "2018-03-16 03:33:00",
										"updateBy": null,
										"updateTime": null,
										"remark": null,
										"dataScope": null,
										"params": {},
										"menuId": 1039,
										"menuName": "操作查询",
										"parentName": null,
										"parentId": 500,
										"orderNum": "1",
										"path": "",
										"component": "",
										"isFrame": "1",
										"menuType": "F",
										"visible": "0",
										"perms": "monitor:operlog:list",
										"icon": "#",
										"children": []
									},
									{
										"searchValue": null,
										"createBy": "admin",
										"createTime": "2018-03-16 03:33:00",
										"updateBy": null,
										"updateTime": null,
										"remark": null,
										"dataScope": null,
										"params": {},
										"menuId": 1040,
										"menuName": "操作删除",
										"parentName": null,
										"parentId": 500,
										"orderNum": "2",
										"path": "",
										"component": "",
										"isFrame": "1",
										"menuType": "F",
										"visible": "0",
										"perms": "monitor:operlog:remove",
										"icon": "#",
										"children": []
									},
									{
										"searchValue": null,
										"createBy": "admin",
										"createTime": "2018-03-16 03:33:00",
										"updateBy": null,
										"updateTime": null,
										"remark": null,
										"dataScope": null,
										"params": {},
										"menuId": 1041,
										"menuName": "详细信息",
										"parentName": null,
										"parentId": 500,
										"orderNum": "3",
										"path": "",
										"component": "",
										"isFrame": "1",
										"menuType": "F",
										"visible": "0",
										"perms": "monitor:operlog:detail",
										"icon": "#",
										"children": []
									},
									{
										"searchValue": null,
										"createBy": "admin",
										"createTime": "2018-03-16 03:33:00",
										"updateBy": null,
										"updateTime": null,
										"remark": null,
										"dataScope": null,
										"params": {},
										"menuId": 1042,
										"menuName": "日志导出",
										"parentName": null,
										"parentId": 500,
										"orderNum": "4",
										"path": "",
										"component": "",
										"isFrame": "1",
										"menuType": "F",
										"visible": "0",
										"perms": "monitor:operlog:export",
										"icon": "#",
										"children": []
									}
								]
							},
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-03-16 03:33:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 501,
								"menuName": "登录日志",
								"parentName": null,
								"parentId": 108,
								"orderNum": "2",
								"path": "logininfor",
								"component": "monitor/logininfor/index",
								"isFrame": "1",
								"menuType": "C",
								"visible": "0",
								"perms": "monitor:logininfor:view",
								"icon": "#",
								"children": [
									{
										"searchValue": null,
										"createBy": "admin",
										"createTime": "2018-03-16 03:33:00",
										"updateBy": null,
										"updateTime": null,
										"remark": null,
										"dataScope": null,
										"params": {},
										"menuId": 1043,
										"menuName": "登录查询",
										"parentName": null,
										"parentId": 501,
										"orderNum": "1",
										"path": "",
										"component": "",
										"isFrame": "1",
										"menuType": "F",
										"visible": "0",
										"perms": "monitor:logininfor:list",
										"icon": "#",
										"children": []
									},
									{
										"searchValue": null,
										"createBy": "admin",
										"createTime": "2018-03-16 03:33:00",
										"updateBy": null,
										"updateTime": null,
										"remark": null,
										"dataScope": null,
										"params": {},
										"menuId": 1044,
										"menuName": "登录删除",
										"parentName": null,
										"parentId": 501,
										"orderNum": "2",
										"path": "",
										"component": "",
										"isFrame": "1",
										"menuType": "F",
										"visible": "0",
										"perms": "monitor:logininfor:remove",
										"icon": "#",
										"children": []
									},
									{
										"searchValue": null,
										"createBy": "admin",
										"createTime": "2018-03-16 03:33:00",
										"updateBy": null,
										"updateTime": null,
										"remark": null,
										"dataScope": null,
										"params": {},
										"menuId": 1045,
										"menuName": "日志导出",
										"parentName": null,
										"parentId": 501,
										"orderNum": "3",
										"path": "",
										"component": "",
										"isFrame": "1",
										"menuType": "F",
										"visible": "0",
										"perms": "monitor:logininfor:export",
										"icon": "#",
										"children": []
									}
								]
							}
						]
					}
				]
			},
			{
				"searchValue": null,
				"createBy": "admin",
				"createTime": "2018-03-16 03:33:00",
				"updateBy": null,
				"updateTime": null,
				"remark": null,
				"dataScope": null,
				"params": {},
				"menuId": 3,
				"menuName": "系统工具",
				"parentName": null,
				"parentId": 1,
				"orderNum": "2",
				"path": "tool",
				"component": null,
				"isFrame": "1",
				"menuType": "M",
				"visible": "0",
				"perms": "",
				"icon": "tool",
				"children": [
					{
						"searchValue": null,
						"createBy": "admin",
						"createTime": "2018-03-16 03:33:00",
						"updateBy": null,
						"updateTime": null,
						"remark": null,
						"dataScope": null,
						"params": {},
						"menuId": 113,
						"menuName": "表单构建",
						"parentName": null,
						"parentId": 3,
						"orderNum": "1",
						"path": "build",
						"component": "tool/build/index",
						"isFrame": "1",
						"menuType": "C",
						"visible": "0",
						"perms": "tool:build:view",
						"icon": "#",
						"children": []
					},
					{
						"searchValue": null,
						"createBy": "admin",
						"createTime": "2018-03-16 03:33:00",
						"updateBy": null,
						"updateTime": null,
						"remark": null,
						"dataScope": null,
						"params": {},
						"menuId": 114,
						"menuName": "代码生成",
						"parentName": null,
						"parentId": 3,
						"orderNum": "2",
						"path": "gen",
						"component": "tool/gen/index",
						"isFrame": "1",
						"menuType": "C",
						"visible": "0",
						"perms": "tool:gen:view",
						"icon": "#",
						"children": [
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-03-16 03:33:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 1056,
								"menuName": "生成查询",
								"parentName": null,
								"parentId": 114,
								"orderNum": "1",
								"path": "",
								"component": "",
								"isFrame": "1",
								"menuType": "F",
								"visible": "0",
								"perms": "tool:gen:list",
								"icon": "#",
								"children": []
							},
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-03-16 03:33:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 1057,
								"menuName": "生成代码",
								"parentName": null,
								"parentId": 114,
								"orderNum": "2",
								"path": "",
								"component": "",
								"isFrame": "1",
								"menuType": "F",
								"visible": "0",
								"perms": "tool:gen:edit",
								"icon": "#",
								"children": []
							},
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-03-16 03:33:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 1058,
								"menuName": "生成删除",
								"parentName": null,
								"parentId": 114,
								"orderNum": "3",
								"path": "",
								"component": "",
								"isFrame": "1",
								"menuType": "F",
								"visible": "0",
								"perms": "tool:gen:remove",
								"icon": "#",
								"children": []
							},
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-03-16 03:33:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 1059,
								"menuName": "预览代码",
								"parentName": null,
								"parentId": 114,
								"orderNum": "4",
								"path": "",
								"component": "",
								"isFrame": "1",
								"menuType": "F",
								"visible": "0",
								"perms": "tool:gen:preview",
								"icon": "#",
								"children": []
							},
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-03-16 03:33:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 1060,
								"menuName": "生成代码",
								"parentName": null,
								"parentId": 114,
								"orderNum": "5",
								"path": "",
								"component": "",
								"isFrame": "1",
								"menuType": "F",
								"visible": "0",
								"perms": "tool:gen:code",
								"icon": "#",
								"children": []
							}
						]
					},
					{
						"searchValue": null,
						"createBy": "admin",
						"createTime": "2018-03-16 03:33:00",
						"updateBy": null,
						"updateTime": null,
						"remark": null,
						"dataScope": null,
						"params": {},
						"menuId": 115,
						"menuName": "系统接口",
						"parentName": null,
						"parentId": 3,
						"orderNum": "3",
						"path": "swagger",
						"component": "tool/swagger/index",
						"isFrame": "1",
						"menuType": "C",
						"visible": "0",
						"perms": "tool:swagger:view",
						"icon": "#",
						"children": []
					}
				]
			},
			{
				"searchValue": null,
				"createBy": "admin",
				"createTime": "2018-03-16 03:33:00",
				"updateBy": null,
				"updateTime": null,
				"remark": null,
				"dataScope": null,
				"params": {},
				"menuId": 2,
				"menuName": "系统监控",
				"parentName": null,
				"parentId": 1,
				"orderNum": "4",
				"path": "monitor",
				"component": null,
				"isFrame": "1",
				"menuType": "M",
				"visible": "0",
				"perms": "",
				"icon": "education",
				"children": [
					{
						"searchValue": null,
						"createBy": "admin",
						"createTime": "2018-03-16 03:33:00",
						"updateBy": null,
						"updateTime": null,
						"remark": null,
						"dataScope": null,
						"params": {},
						"menuId": 109,
						"menuName": "在线用户",
						"parentName": null,
						"parentId": 2,
						"orderNum": "1",
						"path": "online",
						"component": "monitor/online/index",
						"isFrame": "1",
						"menuType": "C",
						"visible": "0",
						"perms": "monitor:online:view",
						"icon": "#",
						"children": [
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-03-16 03:33:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 1046,
								"menuName": "在线查询",
								"parentName": null,
								"parentId": 109,
								"orderNum": "1",
								"path": "",
								"component": "",
								"isFrame": "1",
								"menuType": "F",
								"visible": "0",
								"perms": "monitor:online:list",
								"icon": "#",
								"children": []
							},
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-03-16 03:33:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 1047,
								"menuName": "批量强退",
								"parentName": null,
								"parentId": 109,
								"orderNum": "2",
								"path": "",
								"component": "",
								"isFrame": "1",
								"menuType": "F",
								"visible": "0",
								"perms": "monitor:online:batchForceLogout",
								"icon": "#",
								"children": []
							},
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-03-16 03:33:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 1048,
								"menuName": "单条强退",
								"parentName": null,
								"parentId": 109,
								"orderNum": "3",
								"path": "",
								"component": "",
								"isFrame": "1",
								"menuType": "F",
								"visible": "0",
								"perms": "monitor:online:forceLogout",
								"icon": "#",
								"children": []
							}
						]
					},
					{
						"searchValue": null,
						"createBy": "admin",
						"createTime": "2018-03-16 03:33:00",
						"updateBy": null,
						"updateTime": null,
						"remark": null,
						"dataScope": null,
						"params": {},
						"menuId": 110,
						"menuName": "定时任务",
						"parentName": null,
						"parentId": 2,
						"orderNum": "2",
						"path": "job",
						"component": "monitor/job/index",
						"isFrame": "1",
						"menuType": "C",
						"visible": "0",
						"perms": "monitor:job:view",
						"icon": "#",
						"children": [
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-03-16 03:33:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 1049,
								"menuName": "任务查询",
								"parentName": null,
								"parentId": 110,
								"orderNum": "1",
								"path": "",
								"component": "",
								"isFrame": "1",
								"menuType": "F",
								"visible": "0",
								"perms": "monitor:job:list",
								"icon": "#",
								"children": []
							},
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-03-16 03:33:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 1050,
								"menuName": "任务新增",
								"parentName": null,
								"parentId": 110,
								"orderNum": "2",
								"path": "",
								"component": "",
								"isFrame": "1",
								"menuType": "F",
								"visible": "0",
								"perms": "monitor:job:add",
								"icon": "#",
								"children": []
							},
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-03-16 03:33:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 1051,
								"menuName": "任务修改",
								"parentName": null,
								"parentId": 110,
								"orderNum": "3",
								"path": "",
								"component": "",
								"isFrame": "1",
								"menuType": "F",
								"visible": "0",
								"perms": "monitor:job:edit",
								"icon": "#",
								"children": []
							},
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-03-16 03:33:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 1052,
								"menuName": "任务删除",
								"parentName": null,
								"parentId": 110,
								"orderNum": "4",
								"path": "",
								"component": "",
								"isFrame": "1",
								"menuType": "F",
								"visible": "0",
								"perms": "monitor:job:remove",
								"icon": "#",
								"children": []
							},
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-03-16 03:33:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 1053,
								"menuName": "状态修改",
								"parentName": null,
								"parentId": 110,
								"orderNum": "5",
								"path": "",
								"component": "",
								"isFrame": "1",
								"menuType": "F",
								"visible": "0",
								"perms": "monitor:job:changeStatus",
								"icon": "#",
								"children": []
							},
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-03-16 03:33:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 1054,
								"menuName": "任务详细",
								"parentName": null,
								"parentId": 110,
								"orderNum": "6",
								"path": "",
								"component": "",
								"isFrame": "1",
								"menuType": "F",
								"visible": "0",
								"perms": "monitor:job:detail",
								"icon": "#",
								"children": []
							},
							{
								"searchValue": null,
								"createBy": "admin",
								"createTime": "2018-03-16 03:33:00",
								"updateBy": null,
								"updateTime": null,
								"remark": null,
								"dataScope": null,
								"params": {},
								"menuId": 1055,
								"menuName": "任务导出",
								"parentName": null,
								"parentId": 110,
								"orderNum": "7",
								"path": "",
								"component": "",
								"isFrame": "1",
								"menuType": "F",
								"visible": "0",
								"perms": "monitor:job:export",
								"icon": "#",
								"children": []
							}
						]
					},
					{
						"searchValue": null,
						"createBy": "admin",
						"createTime": "2018-03-16 03:33:00",
						"updateBy": null,
						"updateTime": null,
						"remark": null,
						"dataScope": null,
						"params": {},
						"menuId": 111,
						"menuName": "数据监控",
						"parentName": null,
						"parentId": 2,
						"orderNum": "3",
						"path": "druid",
						"component": "monitor/druid/index",
						"isFrame": "1",
						"menuType": "C",
						"visible": "0",
						"perms": "monitor:data:view",
						"icon": "#",
						"children": []
					},
					{
						"searchValue": null,
						"createBy": "admin",
						"createTime": "2018-03-16 03:33:00",
						"updateBy": null,
						"updateTime": null,
						"remark": null,
						"dataScope": null,
						"params": {},
						"menuId": 112,
						"menuName": "服务监控",
						"parentName": null,
						"parentId": 2,
						"orderNum": "3",
						"path": "server",
						"component": "monitor/server/index",
						"isFrame": "1",
						"menuType": "C",
						"visible": "0",
						"perms": "monitor:server:view",
						"icon": "#",
						"children": []
					}
				]
			}
		]
	}
]
const loadView = (view) => { // 路由懒加载
	return `@/views/${view}`
  }
function filterAsyncRouter(asyncRouterMap) {
	return asyncRouterMap.filter(route => {
	  if (route.component) {
		// Layout组件特殊处理
		if (route.component === 'Layout') {
		  route.component = Layout
		} else {
		  route.component = loadView(route.component)
		}
	  }
	  if (route.children != null && route.children && route.children.length) {
		route.children = filterAsyncRouter(route.children)
	  }
	  return true
	})
  }

console.log(JSON.stringify(filterAsyncRouter(Tree)))